// Generated by CoffeeScript 1.6.3
(function() {
  window.Countdown = (function() {
    function Countdown(type, el, options) {
      var FIVE_DAYS;
      this.type = type;
      this.el = el;
      this.options = options != null ? options : {};
      FIVE_DAYS = 5 * 24 * 60 * 60 * 1000;
      this.to = options.to || new Date(Date.now() + FIVE_DAYS);
      this.leadingZeros = options.leadingZeros || 0;
    }

    Countdown.prototype.run = function() {
      if (this.interval) {
        return;
      }
      this.update();
      return this.interval = setInterval(this.update.bind(this), 1000);
    };

    Countdown.prototype.update = function() {
      var value;
      value = this[this.type]();
      return this.el.innerHTML = this.pad(value);
    };

    Countdown.prototype.stop = function() {
      if (this.interval) {
        clearInterval(this.interval);
      }
      return this.interval = null;
    };

    Countdown.prototype.seconds = function() {
      return this.totalSeconds() % 60;
    };

    Countdown.prototype.minutes = function() {
      return this.totalMinutes() % 60;
    };

    Countdown.prototype.hours = function() {
      return this.totalHours() % 24;
    };

    Countdown.prototype.days = function() {
      return Math.floor(this.totalHours() / 24);
    };

    Countdown.prototype.now = function() {
      return new Date();
    };

    Countdown.prototype.totalSeconds = function() {
      return Math.floor(Math.max(this.to.getTime() - this.now().getTime(), 0) / 1000);
    };

    Countdown.prototype.totalMinutes = function() {
      return Math.floor(this.totalSeconds() / 60);
    };

    Countdown.prototype.totalHours = function() {
      return Math.floor(this.totalMinutes() / 60);
    };

    Countdown.prototype.pad = function(number) {
      number += "";
      while (number.length < this.leadingZeros) {
        number = "0" + number;
      }
      return number;
    };

    return Countdown;

  })();

}).call(this);
